### ISSUE TITLE
.mjml2html is not a function

### ISSUE THREAD

**Issue by ruben-osre** [bures/mjml4-in-browser#2]
I do the following:
``
import { mjml2html } from 'mjml4-in-browser';
mjml2html(..)
``

But suddenly i get the error that the function is not defined. Is something changed?

**Comment by bures** [comment]
I think there has been some tweaks in how mjml2html is exported from mjml. Try this:

```
import mjml2html from 'mjml4-in-browser'; mjml2html(..)
```

**Comment by ruben-osre** [comment]
Works! thanks :)
